Update update-badge.yml

diff --git a/.github/workflows/update-badge.yml b/.github/workflows/update-badge.yml
--- a/.github/workflows/update-badge.yml
+++ b/.github/workflows/update-badge.yml
@@ -13,6 +13,9 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v2
 
+    - name: Display gradle.properties Content
+      run: cat gradle.properties
+
     - name: Set up Java
       uses: actions/setup-java@v2
       with:
@@ -22,6 +25,7 @@ jobs:
     - name: Read Version Number
       id: version
       run: |
+        grep '^version' gradle.properties || echo "Version not found in gradle.properties"
         echo "VERSION=$(grep '^version' gradle.properties | cut -d= -f2)" >> $GITHUB_ENV
         echo "VERSION: ${{ steps.version.outputs.VERSION }}"
 
@@ -40,8 +44,4 @@ jobs:
     - name: Commit and Push Changes
       if: env.CHANGES_DETECTED
       run: |
-        git config user.name "${{ github.actor }}"
-        git config user.email "${{ github.actor }}@users.noreply.github.com"
-        git add README.md
-        git commit -m "Update version badge [skip ci]"
-        git push
+        git config user.name "${{ github.a
